all: ejercicio
barbero:
	g++ barbero_ex.cpp -o barbero_ex HoareMonitor.hpp HoareMonitor.cpp -std=c++11 -I. -lpthread

ejercicio:
	g++ ejercicio2.cpp -o ejercicio2 HoareMonitor.hpp HoareMonitor.cpp -std=c++11 -I. -lpthread

